dist: trusty
language: cpp

compiler:
  - gcc
  - clang

cache: apt

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libglm-dev xorg-dev

install:
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - mkdir build
  - cd build
  - cmake -D BUILD_SHARED_LIBS=ON ..
  - sudo make install
  - cd ..
  - rm build -rf
  - cd ..

script:
  - mkdir build && cd build
  - cmake ..
  - make
