dist: trusty
language: cpp

compiler:
  - gcc
  - clang

cache: apt

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xorg-dev libnoise-dev doxygen

install:
  - git clone -b 3.2.1 --single-branch https://github.com/glfw/glfw.git
  - cd glfw
  - mkdir build
  - cd build
  - cmake -D BUILD_SHARED_LIBS=ON ..
  - sudo make install
  - cd ..
  - rm build -rf
  - cd ..
  - rm glfw -rf

  - git clone -b 0.9.8.4 --single-branch https://github.com/g-truc/glm.git
  - cd glm
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
  - cd ..
  - rm build -rf
  - cd ..
  - rm glm -rf

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - make doc
